site_name: Keystone's FRC Resources

nav:
  - Home: index.md
  - "General":
    - Overview: frc/frc.md
    - "General Resources": frc/general_resources.md
  - Hardware:
    - "How to Use a Drill": hardware/drill.md
  - Software:
    - "Java Basics": software/basics.md
  - Electronics:
    - "Components": electronics/parts.md

theme:
  name: slate
